global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ["172.27.13.104:9100"]
      - targets: ["10.20.206.116:9100"]
      - targets: ["10.20.206.112:9100"]
      - targets: ["10.20.206.201:9100"]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["172.27.13.104:9101"]
      - targets: ["10.20.206.116:9101"]
        labels:
      - targets: ["10.20.206.112:9101"]
      - targets: ["10.20.206.201:9101"]

rule_files:
  - prometheus_alerts_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 172.27.13.104:9093
