all:
  children:
    observer:
      hosts:
        sna-nuc-12:
          ansible_host: 192.168.40.112
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
    target:
      hosts:
        sna-nuc-12:
          ansible_host: 192.168.40.112
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        extreme-edge-1:
         ansible_host: 192.168.40.64
         ansible_ssh_user: i2cat
         ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        sna-nuc-11:
          ansible_host: 192.168.40.114
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        sna-nuc-15:
          ansible_host: 192.168.40.198
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
