all:
  children:
    observer:
      hosts:
        sna-nuc-12:
          ansible_host: 172.27.13.104
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
    target:
      hosts:
        sna-nuc-12:
          ansible_host: 172.27.13.104
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        sna-raspi-2:
         ansible_host: 10.20.206.201
         ansible_ssh_user: i2cat
         ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        sna-nuc-15:
          ansible_host: 10.20.206.112
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
        nvidia-orin:
          ansible_host: 10.20.206.116
          ansible_ssh_user: i2operator
          ansible_ssh_private_key_file: /home/adrian/.ssh/SN-Keypair.pem
